workspace ‘FlexLib.xcworkspace'


target 'FlexLib_Example' do
  workspace ‘FlexLib.xcworkspace'
  xcodeproj ‘FlexLib.xcodeproj'
  pod 'FlexLib', :path => '../'
  pod 'Yoga', '1.14.0'

  target 'FlexLib_Tests' do
    inherit! :search_paths

  pod 'Specta'
  pod 'Expecta'
  end
end


target ‘FlexSwiftDemo’ do
use_frameworks!
  workspace ‘FlexLib.xcworkspace'
  xcodeproj ‘FlexSwiftDemo.xcodeproj'
  pod 'FlexLib', :path => '../'
  pod 'Yoga', '1.14.0'
end



target 'FlexOsxDemo' do
  workspace ‘FlexLib.xcworkspace'
  xcodeproj ‘FlexOsxDemo.xcodeproj'
  pod 'FlexLib', :path => '../'
  pod 'Yoga', '1.14.0'
end
