workspace ‘FlexLib.xcworkspace'

use_frameworks!


target 'FlexLib_Example' do
  workspace ‘FlexLib.xcworkspace'
  xcodeproj ‘FlexLib.xcodeproj'
  pod 'FlexLib', :path => '../'

  target 'FlexLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  end
end


target ‘FlexSwiftDemo’ do
  workspace ‘FlexLib.xcworkspace'
  xcodeproj ‘FlexSwiftDemo.xcodeproj'
  pod 'FlexLib', :path => '../'
end
