workspace ‘FlexLib.xcworkspace'



target 'FlexLib_Example' do
  workspace ‘FlexLib.xcworkspace'
  xcodeproj ‘FlexLib.xcodeproj'
  pod 'FlexLib', :path => '../'
  pod 'FlexLib/preview', :path => '../'

  target 'FlexLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  end
end
